name: ci

on:
  push:
    branches:
      - master_qgis3
    tags-ignore:
      - 'debian/*'
      - '*-start'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    name: test
    runs-on: ubuntu-18.04
    strategy:
        matrix:
            qgis: [ 'master' ]
            python: [ '3.6' ]
    env:
      # Make apt non-interactive by default, and not showing progress
      APT: "apt-get -o Dpkg::Progress=0 -o Dpkg::Use-Pty=0"
      IMAGE: 'elpaso/qgis-testing-environment'
      QGIS_VERSION_TAG: ${{ matrix.qgis }}
      PLUGIN_NAME: "linz-data-importer"
      LDI_LINZ_KEY: ${{ secrets.LDI_LINZ_KEY }}
      LDI_MFE_KEY: ${{ secrets.LDI_MFE_KEY }}
      LDI_NZDF_KEY: ${{ secrets.LDI_NZDF_KEY }}
      LDI_BASEMAPS_KEY: ${{ secrets.LDI_BASEMAPS_KEY }}
    steps:
    - uses: actions/checkout@v2
    - name: Pull docker image
      run: |
        docker pull ${IMAGE}:${QGIS_VERSION_TAG}
    - name: Setup docker container
      run: |
        docker run -d --name qgis-testing-environment \
          -v ${PWD}:/tests_directory \
          -e LDI_LINZ_KEY \
          -e LDI_MFE_KEY \
          -e LDI_NZDF_KEY \
          -e LDI_BASEMAPS_KEY \
          -e DISPLAY=:99 \
          ${IMAGE}:${QGIS_VERSION_TAG}
        sleep 10
        docker exec qgis-testing-environment \
          sh -c "qgis_setup.sh ${PLUGIN_NAME}"
        docker exec qgis-testing-environment \
          sh -c "ln -s /tests_directory /root/.local/share/QGIS/QGIS3/profiles/default/${PLUGIN_NAME}"
    - name: Run test in container
      run: |
        docker exec -t qgis-testing-environment \
          sh -c "qgis_testrunner.sh ${PLUGIN_NAME}.tests.run_tests.run_test_modules"


  deploy:
    name: deploy
    if: startswith(github.ref, 'refs/tags/v')
    needs: [test]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2-beta
        with:
          ref: ${{ github.ref }}
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          echo ${{ github.repository }}
          zip -r linz-data-importer.zip linz-data-importer
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            ${{ github.ref }}]
          draft: true
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./linz-data-importer.zip
          asset_name: linz-data-importer.zip
          asset_content_type: application/zip
      - name: Upload To LINZ DEV QGIS Plugin Repository in AWS
        if: endswith(github.ref, 'UAT')
        run: |
          curl -X POST -H 'Content-Type: application/octet-stream' -H "authorization: bearer ${{ secrets.DEV_PLUGIN_REPO_AUTH }}" --data-binary @linz-data-importer.zip https://plugins.qgis.linz.govt.nz/v1/plugin/linz-data-importer?stage=dev
      - name: Upload To LINZ PRD QGIS Plugin Repository in AWS
        if: false ==  endswith(github.ref, 'UAT')
        run: |
          curl -X POST -H 'Content-Type: application/octet-stream' -H "authorization: bearer ${{ secrets.PRD_PLUGIN_REPO_AUTH }}" --data-binary @linz-data-importer.zip https://plugins.qgis.linz.govt.nz/v1/plugin/linz-data-importer
